import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthWrapper from '@/AuthWrapper'
import AuthReloader from './AuthReloader'
import { ChakraProvider } from '@chakra-ui/react'
import QueryClientWrapper from './QueryClientWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthWrapper>
          <AuthReloader>
            <QueryClientWrapper>
              <ChakraProvider>{children}</ChakraProvider>
            </QueryClientWrapper>
          </AuthReloader>
        </AuthWrapper>
      </body>
    </html>
  )
}
